version: 0.2

phases:
  install:
    java: corretto8
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - mvn   package 
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - target/*.jar
  discard-paths: yes   